name: ecolindk
description: EcoLindk — plateforme de valorisation des déchets recyclables assistée par IA.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^4.14.0
  firebase_auth: ^6.6.1
  cloud_firestore: ^6.0.0
  shared_preferences: ^2.3.3
  permission_handler: ^11.3.1
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  file_selector: ^1.0.3
  geolocator: ^13.0.2
  qr_flutter: ^4.1.0
  share_plus: ^10.1.4
  mobile_scanner: ^6.0.2
  flutter_dotenv: ^6.0.1
  http: ^1.2.2
  google_fonts: ^8.2.1
  remixicon: ^4.9.3
  country_picker: ^2.0.28
  speech_to_text: ^7.5.0
  flutter_tts: ^4.2.0
  flutter_map: ^8.3.2
  latlong2: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  fake_cloud_firestore: ^4.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
