// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw0JkllhxHpw_7AZZj5iK9ZlBdVgH9nY8',
    appId: '1:1022714819094:web:3b8eda9d817b814e297b37',
    messagingSenderId: '1022714819094',
    projectId: 'ecolindk',
    authDomain: 'ecolindk.firebaseapp.com',
    storageBucket: 'ecolindk.firebasestorage.app',
    measurementId: 'G-8SL3RWBQEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjMP122z7RQ1bXmclYw5eYy7sRJU3Jof4',
    appId: '1:1022714819094:android:e9d5ac4516fcc308297b37',
    messagingSenderId: '1022714819094',
    projectId: 'ecolindk',
    storageBucket: 'ecolindk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8o-JSZT71UjHw-mz23L193xs3w3GSzmY',
    appId: '1:1022714819094:ios:738ef9ce9f74373f297b37',
    messagingSenderId: '1022714819094',
    projectId: 'ecolindk',
    storageBucket: 'ecolindk.firebasestorage.app',
    iosClientId:
        '1022714819094-ui0ddhq6is8je2c0n7hb86o77npinc41.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecolindk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8o-JSZT71UjHw-mz23L193xs3w3GSzmY',
    appId: '1:1022714819094:ios:738ef9ce9f74373f297b37',
    messagingSenderId: '1022714819094',
    projectId: 'ecolindk',
    storageBucket: 'ecolindk.firebasestorage.app',
    iosClientId:
        '1022714819094-ui0ddhq6is8je2c0n7hb86o77npinc41.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecolindk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw0JkllhxHpw_7AZZj5iK9ZlBdVgH9nY8',
    appId: '1:1022714819094:web:1f7f4f1cde23d7b7297b37',
    messagingSenderId: '1022714819094',
    projectId: 'ecolindk',
    authDomain: 'ecolindk.firebaseapp.com',
    storageBucket: 'ecolindk.firebasestorage.app',
    measurementId: 'G-50CJQVK20W',
  );
}
